Create ProjectOverview.md
sandiego-rh/sandiego pull request #147
Opened 2022-05-17 19:25 UTC by bproffitt

@cdolfi Please review for content focus, missing information. Thanks!

2022-05-18 16:37 UTC, cdolfi requested changes

2022-05-18 16:37 UTC, cdolfi commented on ProjectOverview.md
> +* Cauldron (Github data collection software based on Kibana and OpenElastic)
would take this out

2022-05-18 16:37 UTC, cdolfi commented on ProjectOverview.md
> +### Dataset
Data set might be a bit misleading here. Maybe "Open source Ecosystem Mapping"? A little wordy, open to some spit balling

2022-05-18 16:37 UTC, cdolfi commented on ProjectOverview.md
> +Repo: [https://github.com/OSAS/sandiego](https://github.com/OSAS/sandiego)
Update to current repo links

2022-05-25 16:18 UTC, cdolfi commented
@bproffitt bumping for changes

2022-05-26 15:30 UTC, bproffitt commented on ProjectOverview.md
> +* Identify and monitor projects within the surrounding ecosystem to identify issues
Yes, I think that works. Though instead of "surrounding", maybe "related" or "adjacent".

2022-05-26 15:33 UTC, bproffitt commented on ProjectOverview.md
> +* Cauldron (Github data collection software based on Kibana and OpenElastic)
Yes

2022-05-26 15:33 UTC, bproffitt commented on ProjectOverview.md
> +### Dataset
Ecosystem Mapping would be enough

2022-05-26 15:34 UTC, bproffitt reviewed
Approved with my comments.

2022-05-26 17:48 UTC, merged