Adding app and notebook
sandiego-rh/sandiego pull request #159
Opened 2022-07-19 21:24 UTC by yuunlee

2022-07-21 15:28 UTC, cdolfi requested changes

2022-07-21 15:28 UTC, cdolfi commented on models/density_metrics/activities.py
> +    dff = df4[df4['org'] == select_continent]
also change variable names of df and df4 to be related to the data

2022-07-21 15:28 UTC, cdolfi commented on models/density_metrics/activities.py
> +    Input(component_id='select_continent', component_property='value')
same as above

2022-07-21 15:28 UTC, cdolfi commented on models/density_metrics/activities.py
> +        # print(f'hover data: {hov_data}')
remove this comment

2022-07-21 15:28 UTC, cdolfi commented on models/density_metrics/communities.py
> +    [Input(component_id='select_continent', component_property='value')]
Same as above, go through all of the variable names in code to make the correlate to the data/components at hand

2022-07-21 15:28 UTC, cdolfi commented on models/density_metrics/communities.py
> +    # input_data = df_pr_authors[df_pr_authors['rg_name'] == select_continent]
remove comment here

2022-07-21 15:28 UTC, cdolfi commented on models/density_metrics/df/df_activities.py
> +with open("/home/yunlee/Desktop/config.json") as config_file:
look at explorer or reach out to james or I if you have question on this. this should be a file path that could be used by anyone. I would add a comment explaining where in the file someone should put their config to have this work

2022-07-21 15:28 UTC, cdolfi commented on models/density_metrics/df/df_activities.py
> +repo_query = salc.sql.text(f"""
add a comment here explaining this query and the data it gets

2022-07-21 15:28 UTC, cdolfi commented on models/density_metrics/index.py
> +    Output('select_countries', 'options'),
change variable names here too

2022-07-21 15:28 UTC, cdolfi commented on models/density_metrics/index.py
> +import dash_bootstrap_components as dbc
move this code to app.py. Look at https://github.com/sandiego-rh/explorer/blob/main/app.py for inspiration. As well on how to set up a multipage dash app. Reach out to james or myself with any questions/help on setting this up

2022-07-21 15:28 UTC, cdolfi commented on models/density_metrics/performances.py
> +performances_layout = html.Div([
use a dbc.container here instead of div

2022-07-21 15:29 UTC, cdolfi commented
@yuunlee reach out to me with any questions! Overall look at updating variables, adding comments to your code explaining the sections, and then the structural changes in the review. Let me know if you need any help!

2022-07-28 19:33 UTC, yuunlee commented on models/density_metrics/index.py
> +import dash_bootstrap_components as dbc
Updated the change in app.py and multipage set up: https://github.com/sandiego-rh/sandiego/compare/main...yuunlee:sandiego:test-density

2022-07-29 21:13 UTC, JamesKunstle submitted a review, later dismissed
I would really love to see thorough documentation in your jupyter notebook about:

1. What you're hoping to show, at a very very high level, e.g. "There are projects inside of organizations that receive more attention than others. We would like to quantify this difference by modeling a statistical model called love-orbit that analyzes contributor interaction data of different kinds." 
2. What each of the motivations are for your assumptions, including how you break down your notebook as a research project. I'm lost on the importance of large sections of your notebook because I don't know why you're doing somethings. 
3. Defining what a successful outcome would be for this work at the bottom, what you've shown, and what the motivation would be for the app that you're going to go on to create.

In the pages of your app, I would like to see similar documentation. You could also summarize a lot of the work in written format in the README that would help the reader understand the work that you've done.

2022-08-01 17:24 UTC, cdolfi commented
@yuunlee is dframe_perc a table with every single repo in the data base or only the information based on search bar selection?

2022-08-01 18:03 UTC, cdolfi requested changes

2022-08-01 19:28 UTC, cdolfi requested changes
So this is my comments through getting the app running locally and looking at the activity page. I cant navigate to the other pages so I can not review that yet

2022-08-01 19:28 UTC, cdolfi commented on models/density_metrics/pages/activities.py
> +        breakdown_fig = go.Figure(
Remove "increase in" from the names. Implied from the graph

2022-08-01 19:28 UTC, cdolfi commented on models/density_metrics/pages/activities.py
> +            ]
edit the hover information. The action type does not need to be listed as it is identified by they color of bar. Have the data and count listed. An example of this can be seen here https://github.com/sandiego-rh/explorer/blob/main/pages/visualizations/chaoss/contributors_over_time.py "hovertemplate

2022-08-01 19:28 UTC, cdolfi commented on models/density_metrics/pages/activities.py
> +def update_side_graph(clk_data, select_org):
Is this graph only suppose to be showing only 3 months? If so edit view to only include that in view

2022-08-01 19:35 UTC, yuunlee commented on models/density_metrics/pages/activities.py
> +        breakdown_fig = go.Figure(
I guess in this section, I'm trying to emphasize it's not the number of PR/ issue/ star, but the PR/ issue/ star increment compared to last existing month. Is there a better way to address this?

2022-08-01 19:47 UTC, cdolfi commented on models/density_metrics/pages/activities.py
> +        breakdown_fig = go.Figure(
So for this graph, the bar value is the number of new PR/issue/Stars from that month? Or something different?

2022-08-04 15:35 UTC, yuunlee commented on models/density_metrics/pages/activities.py
> +def update_side_graph(clk_data, select_org):
I did not intentionally set to show only 3 months. However, this graph tends to show the "comparison with last month", so if there're four months of data (Jan, Apr, Jun, July), it would set Jan as the baseline, and display the increment/ decrement of April compared to January, June compared to April, and July compared to June. But it indeed is weird that there's few data than I expected. For example, the repo_id = 27835 is the repo for kubernetes under kubernetes org. If I simply do a select on `SELECT * FROM repo_info WHERE repo_id = 27835`, data starts from January 2022, which is a bit too recent? @cdolfi

2022-08-05 14:34 UTC, yuunlee commented on models/density_metrics/pages/activities.py
> +        breakdown_fig = go.Figure(
Yes! The bar value is the number of new PR/issue/Stars (times the assigned weight for each activity) for that month compared to the previous month. (The prevous month might not be exactly a month ago, it's just previous month with data)

2022-08-05 15:41 UTC, cdolfi requested changes

2022-08-05 15:56 UTC, cdolfi commented on models/density_metrics/pages/activities.py
> +        breakdown_fig = go.Figure(
Okay sounds good, If you chance the title to "Selected Repo Activity by Month" and take out the "increase in" that will get the message across! Increased by is a little wordy and could also be confusing as they might think it implies the delta. Also, instead of having "selected repo" and the name underneath, dash actually allows you to have variable titles! this is an example but I can also show you on a call https://github.com/sandiego-rh/explorer/blob/main/pages/visualizations/chaoss/contrib_drive_repeat.py

2022-08-09 17:39 UTC, yuunlee commented
Communities:
- I found the key I used for connecting "contributors" and "commits" table might be wrong. But I couldn't find a key that is able to correctly connect the two tables, and that is likely the reason for the cause for ansible/ansible. Might need some help on that. @cdolfi

2022-08-11 20:35 UTC, cdolfi approved these changes

2022-08-11 20:37 UTC, merged